// Code generated by MockGen. DO NOT EDIT.
// Source: service/booking/bookingRequest.go

// Package booking is a generated GoMock package.
package booking

import (
	entity "hotel-api/entity"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckRoomAvailability mocks base method.
func (m *MockRepository) CheckRoomAvailability(roomID int, checkIn, checkOut time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRoomAvailability", roomID, checkIn, checkOut)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRoomAvailability indicates an expected call of CheckRoomAvailability.
func (mr *MockRepositoryMockRecorder) CheckRoomAvailability(roomID, checkIn, checkOut interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRoomAvailability", reflect.TypeOf((*MockRepository)(nil).CheckRoomAvailability), roomID, checkIn, checkOut)
}

// CreateBooking mocks base method.
func (m *MockRepository) CreateBooking(booking *entity.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockRepositoryMockRecorder) CreateBooking(booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockRepository)(nil).CreateBooking), booking)
}

// DeleteBooking mocks base method.
func (m *MockRepository) DeleteBooking(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooking", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooking indicates an expected call of DeleteBooking.
func (mr *MockRepositoryMockRecorder) DeleteBooking(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooking", reflect.TypeOf((*MockRepository)(nil).DeleteBooking), id)
}

// GetBookingByID mocks base method.
func (m *MockRepository) GetBookingByID(id string) (entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByID", id)
	ret0, _ := ret[0].(entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByID indicates an expected call of GetBookingByID.
func (mr *MockRepositoryMockRecorder) GetBookingByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByID", reflect.TypeOf((*MockRepository)(nil).GetBookingByID), id)
}

// GetMyBookings mocks base method.
func (m *MockRepository) GetMyBookings(userID int) ([]entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyBookings", userID)
	ret0, _ := ret[0].([]entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyBookings indicates an expected call of GetMyBookings.
func (mr *MockRepositoryMockRecorder) GetMyBookings(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyBookings", reflect.TypeOf((*MockRepository)(nil).GetMyBookings), userID)
}

// UpdateBooking mocks base method.
func (m *MockRepository) UpdateBooking(id string, booking *entity.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBooking", id, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBooking indicates an expected call of UpdateBooking.
func (mr *MockRepositoryMockRecorder) UpdateBooking(id, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBooking", reflect.TypeOf((*MockRepository)(nil).UpdateBooking), id, booking)
}
